### ISSUE TITLE
[Website] Installer requires Win7 SP1, but website mentions XP

### ISSUE THREAD

**Issue by Tarnyko** [freenet/wininstaller-innosetup#15]
Website [download page](https://freenetproject.org/fr/pages/download.html) mentions "_Freenet requires Windows XP or later._", but it seems to require [Windows 7 SP1](http://www.tarnyko.net/repo/FreenetInstaller.jpg) instead.

**Comment by desyncr** [comment]
Newer innosetup defaults to Windows 7 SP1.

Ref:
- https://github.com/jrsoftware/issrc/commit/d1fd254b00e295c7710acc881f4ba244aadb04ae
- https://github.com/jrsoftware/issrc/commit/d1d14e6155ae68ce388a504e81dd5f3b6a03c02a

**Comment by desyncr** [comment]
@ArneBab We should update the documentation where required (AFAIK https://github.com/freenet/website and some references on the Wiki).

Let me know what you think and I'll move it forward.

**Comment by ArneBab** [comment]
@desyncr you’re right, yes. Would be awesome if you’d do it!

**Comment by desyncr** [comment]
@ArneBab Updated docs and Wiki pages:
- https://github.com/freenet/wiki/wiki/Installing-on-Windows
- https://github.com/freenet/wiki/wiki/Projects

**Comment by ArneBab** [comment]
I now also updated the French and Russian translation.
