### ISSUE TITLE
HELP pls

### ISSUE THREAD

**Issue by Minionguyjpro** [freenet/wininstaller-innosetup#16]
When i try to run the workflow it says the following by trying to sign it:
``The value for "credentials" is not set.
Downloading signtool.exe.
The value for "certificate" is not set.
(node:2192) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, unlink 'C:\Users\RUNNER~1\AppData\Local\Temp\creds.json'
    at Object.unlinkSync (fs.js:1035:3)
    at run (D:\a\_actions\nextgens\authenticode-sign-action\v1.0.1\dist\index.js:1:112844)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2192) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2192) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.``

**Comment by Thynix** [comment]
Without a code signing certificate, you're not going to be able to run that step. Do you have one and it's failing anyway?

**Comment by Minionguyjpro** [comment]
How to make one?

**Comment by Minionguyjpro** [comment]
And how to push that to GitHub? Because when i try to run without signing i dont see an output build on GitHub.

**Comment by Thynix** [comment]
You're welcome to try to do this, but unless you find a problem with this repo specifically, filing a bug against it is not the place to get help.
